// // System.
// using System;
// using System.Collections;
// using System.Collections.Generic;
// using System.Threading.Tasks;
// // Unity.
// using UnityEngine;
// using UnityEditor;
// // Sirenix.
// using Sirenix.OdinInspector;

// namespace SneakerWorld.Admin {

//     using SneakerData = SneakerWorld.Main.SneakerData;
//     using Rarity = SneakerWorld.Main.Rarity;

//     /// <summary>
//     /// A class to allow building sneakers to store in firebase, from within unity.
//     /// </summary>
//     [ExecuteInEditMode, CreateAssetMenu(fileName="sneaker_name_rarity", menuName="Items/Sneaker")]
//     public class SneakerObject : ScriptableObject {

//         // Generated by the object.
//         public string debugId = "";

//         // The details of this crate.
//         public new string name;
//         public Rarity rarity;
//         public int price;
//         public int level;
//         // public Sprite icon;

//         // Runs only while in edit mode when a value is changed.
//         void OnValidate() {
//             // name = Path.GetFileNameWithoutExtension(AssetDatabase.GetAssetPath(this));
//             debugId = SneakerData.GetSneakerId(name, rarity);
//         }

//         // Create the actual crate data from the settings of this builder.
//         public SneakerData ToData() {
//             SneakerData sneakerData = new SneakerData();
//             sneakerData.name = name;
//             sneakerData.rarity = rarity;
//             sneakerData.price = price;
//             sneakerData.level = level;
//             // sneakerData.imagePath = AssetDatabase.GetAssetPath(icon).Replace("Assets/Resources/", "").Replace(".png", "");
//             return sneakerData;
//         }
        
//     }

// }

